### ISSUE TITLE
Xcode 14.3 (14E222b) class NotificationService: DTDMediaAttachmentExtension  use old swift 

### ISSUE THREAD

**Issue by frbodya** [devtodev-analytics/package_Messaging#1]
Failed to build module 'DTDMessagingUnity'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.

**Comment by kaikristo** [comment]
Which version of xcode are you using? 14.3 RC?

**Comment by frbodya** [comment]
no, just stable Xcode 14.3
Build version 14E222b
swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

**Comment by frbodya** [comment]
I also notice, that 
DTDMessaging.IOS.Initialize(); is missing, so I don't call it

**Comment by frbodya** [comment]
issue with step: In the NotificationService class (in the folder named after your target), replace the code with the following:

**Comment by kaikristo** [comment]
As we can see many users faced with this problem, we recommended use xcode 14.2 release for now. We will update the thread when we have more information.

**Comment by frbodya** [comment]
14_2 I have same error, as it use swift 5.7, latest with swift 5.6.1 Xcode_13.4.1, but I couldn't run it on Venture :(

**Comment by kaikristo** [comment]
Fixed in the 3.6.3 version.
