### ISSUE TITLE
No Push Notifications option in Configuration, only Analytics

### ISSUE THREAD

**Issue by ORibn-dev** [devtodev-analytics/package_Messaging#2]
I installed Analytics and Messaging 3.4.3 using Package Manager:
https://github.com/devtodev-analytics/package_Analytics.git
https://github.com/devtodev-analytics/package_Messaging.git
Unity 2020.3.48f1

https://i.imgur.com/CoHXqs4.png
But configuration setting shows only Analytics option and no Push Notifications one that's supposed to be there. Did I miss something?

**Comment by kaikristo** [comment]
Messaging module dont have the gui. Use code initialization instead https://docs.devtodev.com/integration/integration-of-sdk-v2/push-notifications/unity
